using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using VendorOfferUpdater.Models;

namespace VendorOfferUpdater
{
    /// <summary>
    /// Builds ref/recipe_sheet_items.json: the recipe id to unlocking
    /// sheet item id map that Services/RecipeSheetSavingsCalculator.cs
    /// needs before it can price a missing recipe.
    /// <para>
    /// The GW2 API states the link from the item side only. GET
    /// /v2/items/:id returns details.recipe_id when details.type is Unlock
    /// and details.unlock_type is CraftingRecipe. Nothing under ref/
    /// carries it, so the map is built by asking the bulk endpoint about
    /// every item ref/vendor_offers.json already sells and keeping the
    /// answers that are recipe sheets.
    /// </para>
    /// <para>
    /// No wiki traffic, and no name matching. A sheet named "Recipe: X" is
    /// not evidence that it teaches the recipe producing X.
    /// </para>
    /// </summary>
    internal static class RecipeSheetMapBuilder
    {
        /// <summary>
        /// The GW2 API's documented cap on ids per /v2 bulk request. Same
        /// number Gw2ApiHelper.LoadCurrenciesAsync and
        /// tools/TaimisToolbench.RecipeSeeder already batch at.
        /// </summary>
        internal const int ItemBatchSize = 200;

        private const string ItemsUrl = "https://api.guildwars2.com/v2/items";

        private const string SourceText =
            "api.guildwars2.com /v2/items. Generated by tools/VendorOfferUpdater " +
            "--build-recipe-sheet-map, which asks the bulk item endpoint about every " +
            "item ref/vendor_offers.json sells, 200 ids per request. An item is a " +
            "recipe sheet when details.type is Unlock and details.unlock_type is " +
            "CraftingRecipe; its details.recipe_id is the recipe it teaches. That is " +
            "the only place the GW2 API states this link, and no file under ref/ " +
            "carries it. craftedItemId, disciplines and minRating are read back from " +
            "ref/recipes_seed.json, and craftedItemName from ref/item_name_seed.json; " +
            "an entry omits them when the recipe is not in those seeds.";

        /// <summary>
        /// Reads the shipped offers, resolves every sheet among them and
        /// writes the map. Returns a process exit code.
        /// </summary>
        internal static async Task<int> RunAsync(
            string repoRoot, HttpClient httpClient, int delayMs, bool allowCoverageDrop, CancellationToken ct)
        {
            string refDir = Path.Combine(repoRoot, "ref");
            string offersPath = Path.Combine(refDir, "vendor_offers.json");
            string outputPath = Path.Combine(refDir, "recipe_sheet_items.json");

            if (!File.Exists(offersPath))
            {
                Console.Error.WriteLine($"ERROR: vendor offers not found at {offersPath}.");
                return 1;
            }

            Console.WriteLine($"Reading vendor offers from {offersPath}...");
            var soldItemIds = ReadSoldItemIds(offersPath);
            Console.WriteLine($"  {soldItemIds.Count} distinct items are sold by a vendor.");

            int batches = (soldItemIds.Count + ItemBatchSize - 1) / ItemBatchSize;
            Console.WriteLine(
                $"Asking {ItemsUrl} about them, {ItemBatchSize} ids per request " +
                $"({batches} requests)...");

            var sheets = await ResolveSheetsAsync(soldItemIds, httpClient, delayMs, ct);
            Console.WriteLine($"  {sheets.Count} of them are recipe sheets.");

            var entries = BuildEntries(sheets, refDir, out int recipesWithMoreThanOneSheet);
            if (recipesWithMoreThanOneSheet > 0)
            {
                Console.WriteLine(
                    $"  {recipesWithMoreThanOneSheet} recipe(s) are taught by more than one " +
                    "sold sheet; each keeps the lowest sheet item id.");
            }

            int shipped = CountShippedEntries(outputPath);
            if (entries.Count < shipped && !allowCoverageDrop)
            {
                Console.Error.WriteLine(
                    $"ERROR: this run resolved {entries.Count} sheets and {outputPath} already " +
                    $"holds {shipped}. A shrinking map is how a bad API response blanks a file " +
                    "nothing else can rebuild. Nothing was written. Pass --allow-coverage-drop " +
                    "once you know the corpus really did shrink.");
                return 3;
            }

            string json = Serialize(entries);
            await File.WriteAllTextAsync(outputPath, json, ct);
            Console.WriteLine($"Written {entries.Count} entries to {outputPath}");
            return 0;
        }

        /// <summary>
        /// How many entries the file already on disk holds, or 0 when it is
        /// absent or unreadable. A first run has nothing to compare against.
        /// </summary>
        internal static int CountShippedEntries(string outputPath)
        {
            if (!File.Exists(outputPath))
            {
                return 0;
            }

            try
            {
                using var document = JsonDocument.Parse(File.ReadAllText(outputPath));
                return document.RootElement.TryGetProperty("items", out var items) &&
                       items.ValueKind == JsonValueKind.Array
                    ? items.GetArrayLength()
                    : 0;
            }
            catch (JsonException)
            {
                return 0;
            }
        }

        /// <summary>
        /// Every distinct outputItemId in the offers file, ascending, so a
        /// rerun batches the same ids in the same order.
        /// </summary>
        internal static List<int> ReadSoldItemIds(string offersPath)
        {
            var readOptions = new JsonSerializerOptions
            {
                PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
                PropertyNameCaseInsensitive = true,
            };

            var dataset = JsonSerializer.Deserialize<VendorOfferDataset>(
                File.ReadAllText(offersPath), readOptions) ?? new VendorOfferDataset();

            return dataset.Offers
                .Select(o => o.OutputItemId)
                .Where(id => id > 0)
                .Distinct()
                .OrderBy(id => id)
                .ToList();
        }

        /// <summary>
        /// Asks the bulk item endpoint about every id and keeps the recipe
        /// sheets. A batch the API answers 404 for holds no id it knows, so
        /// it contributes nothing and is not an error.
        /// </summary>
        internal static async Task<List<ResolvedSheet>> ResolveSheetsAsync(
            IReadOnlyList<int> itemIds, HttpClient httpClient, int delayMs, CancellationToken ct)
        {
            var sheets = new List<ResolvedSheet>();

            for (int start = 0; start < itemIds.Count; start += ItemBatchSize)
            {
                ct.ThrowIfCancellationRequested();

                var batch = itemIds.Skip(start).Take(ItemBatchSize).ToList();
                string url = ItemsUrl + "?ids=" + string.Join(",", batch);

                using var response = await httpClient.GetAsync(url, ct);
                if (response.StatusCode == HttpStatusCode.NotFound)
                {
                    continue;
                }

                response.EnsureSuccessStatusCode();
                string body = await response.Content.ReadAsStringAsync();
                sheets.AddRange(ParseSheets(body));

                if (delayMs > 0 && start + ItemBatchSize < itemIds.Count)
                {
                    await Task.Delay(delayMs, ct);
                }
            }

            return sheets;
        }

        /// <summary>
        /// Reads one /v2/items response body and returns the recipe sheets
        /// in it. An element missing any of the three details fields is not
        /// a sheet and is skipped without comment.
        /// </summary>
        internal static List<ResolvedSheet> ParseSheets(string responseBody)
        {
            var sheets = new List<ResolvedSheet>();
            using var document = JsonDocument.Parse(responseBody);
            if (document.RootElement.ValueKind != JsonValueKind.Array)
            {
                return sheets;
            }

            foreach (var element in document.RootElement.EnumerateArray())
            {
                if (element.ValueKind != JsonValueKind.Object ||
                    !element.TryGetProperty("id", out var idElement) ||
                    idElement.ValueKind != JsonValueKind.Number ||
                    !element.TryGetProperty("details", out var details) ||
                    details.ValueKind != JsonValueKind.Object)
                {
                    continue;
                }

                if (!IsStringValue(details, "type", "Unlock") ||
                    !IsStringValue(details, "unlock_type", "CraftingRecipe") ||
                    !details.TryGetProperty("recipe_id", out var recipeElement) ||
                    recipeElement.ValueKind != JsonValueKind.Number)
                {
                    continue;
                }

                sheets.Add(new ResolvedSheet(
                    idElement.GetInt32(),
                    recipeElement.GetInt32(),
                    element.TryGetProperty("name", out var nameElement) &&
                        nameElement.ValueKind == JsonValueKind.String
                        ? nameElement.GetString()
                        : null));
            }

            return sheets;
        }

        /// <summary>
        /// One entry per recipe id, ascending. A recipe taught by more than
        /// one sold sheet keeps the lowest sheet item id, because the seed
        /// loader holds one sheet per recipe and an arbitrary winner would
        /// change between runs.
        /// </summary>
        internal static List<RecipeSheetEntry> BuildEntries(
            IReadOnlyList<ResolvedSheet> sheets, string refDir, out int recipesWithMoreThanOneSheet)
        {
            var recipes = RecipeSeedFacts.Load(Path.Combine(refDir, "recipes_seed.json"));
            var itemNames = ItemNameSeed.Load(Path.Combine(refDir, "item_name_seed.json"));

            var bySheet = new Dictionary<int, ResolvedSheet>();
            foreach (var sheet in sheets.OrderBy(s => s.SheetItemId))
            {
                bySheet.TryAdd(sheet.RecipeId, sheet);
            }

            recipesWithMoreThanOneSheet =
                sheets.GroupBy(s => s.RecipeId).Count(g => g.Select(s => s.SheetItemId).Distinct().Count() > 1);

            var entries = new List<RecipeSheetEntry>(bySheet.Count);
            foreach (var pair in bySheet.OrderBy(p => p.Key))
            {
                var entry = new RecipeSheetEntry
                {
                    RecipeId = pair.Key,
                    SheetItemId = pair.Value.SheetItemId,
                    SheetItemName = pair.Value.SheetItemName,
                };

                if (recipes.TryGetValue(pair.Key, out var recipe))
                {
                    entry.CraftedItemId = recipe.OutputItemId;
                    entry.Disciplines = recipe.Disciplines;
                    entry.MinRating = recipe.MinRating;
                    if (itemNames.TryGetValue(recipe.OutputItemId, out string? craftedName))
                    {
                        entry.CraftedItemName = craftedName;
                    }
                }

                entries.Add(entry);
            }

            return entries;
        }

        internal static string Serialize(IReadOnlyList<RecipeSheetEntry> entries)
        {
            var document = new RecipeSheetDocument
            {
                SchemaVersion = 1,
                GeneratedAt = DateTime.UtcNow.ToString("o", CultureInfo.InvariantCulture),
                Source = SourceText,
                Items = entries.ToList(),
            };

            // Same encoder pairing ref/vendor_offers.json uses: the relaxed
            // encoder leaves an apostrophe or an ampersand in an item name
            // alone, and EscapeNonAscii below turns everything above U+007F
            // into a lowercase \uXXXX. The default encoder escapes both, so
            // the two generated files would disagree on their own bytes.
            var options = new JsonSerializerOptions
            {
                PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
                WriteIndented = true,
                DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
                Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
            };

            string json = Program.EscapeNonAscii(JsonSerializer.Serialize(document, options));
            return json.Replace("\r\n", "\n") + "\n";
        }

        private static bool IsStringValue(JsonElement parent, string property, string expected)
        {
            return parent.TryGetProperty(property, out var value) &&
                   value.ValueKind == JsonValueKind.String &&
                   string.Equals(value.GetString(), expected, StringComparison.Ordinal);
        }

        /// <summary>One recipe sheet, as the item endpoint described it.</summary>
        internal sealed class ResolvedSheet
        {
            internal ResolvedSheet(int sheetItemId, int recipeId, string? sheetItemName)
            {
                SheetItemId = sheetItemId;
                RecipeId = recipeId;
                SheetItemName = sheetItemName;
            }

            internal int SheetItemId { get; }

            internal int RecipeId { get; }

            internal string? SheetItemName { get; }
        }

        internal sealed class RecipeSheetDocument
        {
            public int SchemaVersion { get; set; }

            public string GeneratedAt { get; set; } = string.Empty;

            public string Source { get; set; } = string.Empty;

            public List<RecipeSheetEntry> Items { get; set; } = new List<RecipeSheetEntry>();
        }

        internal sealed class RecipeSheetEntry
        {
            public int RecipeId { get; set; }

            public int SheetItemId { get; set; }

            public string? SheetItemName { get; set; }

            public int? CraftedItemId { get; set; }

            public string? CraftedItemName { get; set; }

            public List<string>? Disciplines { get; set; }

            public int? MinRating { get; set; }
        }
    }
}
