#!/usr/bin/env python3
"""Census and ratchet for over-length comment blocks in tracked .cs files.

    python3 tools/comment-budgets.py > docs/comment-budgets.txt   # re-pin
    python3 tools/comment-budgets.py --check                      # what CI runs

The counting and the checking are the same code on purpose: a generator in
tools/ paired with a re-implementation inside the workflow YAML would drift,
and the drift would show up as a green build rather than a failure.
"""

import argparse
import os
import subprocess
import sys

# CLAUDE.md: "roughly 12 lines of inline // prose".
INLINE_MAX = 12

# Looser than the inline rule, because the same prose costs more lines here:
# an XML block spends them on <summary>, <para>, <list> and <param> structure
# that a // block does not have to write. Not much looser. Measured over the
# 2,257 XML runs in the tree: median 7 lines, mean 8.9, p90 19, p99 40. The
# previous 40 sat at the 99th percentile, so it constrained 1% of blocks and
# an author who learned the limit from a CI failure learned the wrong number
# - CLAUDE.md has said 12 the whole time. 20 sits just above p90, leaving
# ~92% of existing blocks compliant and putting the gate where a block has
# to earn its length.
XML_MAX = 20

HEADER = """\
# Per-file counts of over-length comment blocks - a ratchet, not a target.
#
# Why this file exists: the August 2026 comment sweep (d7df9fb, 810414f,
# 4632d45) went after session jargon, duplicated rationale and audit-row
# narration, and cut the number of inline blocks over 12 lines by three.
# Block length was never the metric, so the long blocks that survived the
# sweep were never counted, and nothing in CI could tell a 50-line comment
# from 50 lines of code.
#
# How to read it: every entry is the number of over-length comment blocks a
# file contained on the day it was added. CI fails when a file exceeds its
# entry, or when a file has violations and no entry at all. Nothing here is
# a goal to optimise towards; growth is simply not free any more.
#
# A block is a contiguous run of comment-only lines, broken by any line that
# is not one - including a blank line, and including a switch between the
# two categories, which are counted separately:
#
#   inline  lines starting with // (but not ///), over %(inline)d lines
#   xml     lines starting with ///, over %(xml)d lines
#
# The distinction is the point. A long XML block documents a type; long
# inline narration is the thing CLAUDE.md's 12-line rule is aimed at.
#
# Lowering a count is the explicit act of a cleanup commit - re-pin with the
# command at the top of tools/comment-budgets.py, in that same commit.
# Raising one is allowed and should say in the commit message why the
# comment earned the length.
#
# Only tracked .cs files are counted, module and tests/ and tools/ alike.
# Files with no over-length block are not listed. An entry whose path no
# longer exists fails, so a rename has to re-anchor its counts rather than
# silently drop them.
#
# Generated by tools/comment-budgets.py - edit the header there, not here.
# Format: <path> <inline-blocks-over-%(inline)d> <xml-blocks-over-%(xml)d>.\
""" % {"inline": INLINE_MAX, "xml": XML_MAX}


def tracked_sources():
    out = subprocess.run(["git", "ls-files", "*.cs"], capture_output=True,
                         text=True, check=True).stdout.split()
    return sorted(out)


def over_length_blocks(path):
    """Return [(category, length, first_line), ...] for the file's long runs."""
    with open(path, encoding="utf-8", errors="replace") as handle:
        lines = handle.read().splitlines()

    blocks = []
    category, length, start = None, 0, 0

    def close():
        limit = INLINE_MAX if category == "inline" else XML_MAX
        if category is not None and length > limit:
            blocks.append((category, length, start))

    for number, line in enumerate(lines, 1):
        text = line.strip()
        if text.startswith("///"):
            kind = "xml"
        elif text.startswith("//"):
            kind = "inline"
        else:
            kind = None

        if kind is not None and kind == category:
            length += 1
            continue
        close()
        category, length, start = kind, 1 if kind else 0, number

    close()
    return blocks


def census():
    """Return {path: {"inline": n, "xml": n}} for files with any violation."""
    counts = {}
    for path in tracked_sources():
        if not os.path.isfile(path):
            continue
        tally = {"inline": 0, "xml": 0}
        for category, _, _ in over_length_blocks(path):
            tally[category] += 1
        if tally["inline"] or tally["xml"]:
            counts[path] = tally
    return counts


def render(counts):
    lines = [HEADER]
    for path in sorted(counts):
        tally = counts[path]
        lines.append("%-90s%4d%6d" % (path, tally["inline"], tally["xml"]))
    return "\n".join(lines) + "\n"


def read_pins(pin_path):
    pins = {}
    if not os.path.isfile(pin_path):
        sys.exit("%s does not exist. Seed it with:\n"
                 "  python3 tools/comment-budgets.py > %s" % (pin_path, pin_path))
    with open(pin_path, encoding="utf-8") as handle:
        for number, line in enumerate(handle, 1):
            if not line.strip() or line.lstrip().startswith("#"):
                continue
            fields = line.split()
            if len(fields) != 3:
                sys.exit("%s:%d: expected '<path> <inline> <xml>', got: %s"
                         % (pin_path, number, line.strip()))
            path, inline, xml = fields
            if path in pins:
                # A second entry silently overrides the first, which would let a
                # raise land as an appended line rather than an edited one.
                sys.exit("%s:%d: duplicate entry for %s" % (pin_path, number, path))
            try:
                pins[path] = {"inline": int(inline), "xml": int(xml)}
            except ValueError:
                sys.exit("%s:%d: counts must be integers: %s"
                         % (pin_path, number, line.strip()))
    return pins


def pinned_header(pin_path):
    """The leading comment block of the pin file, as the generator would write it."""
    kept = []
    with open(pin_path, encoding="utf-8") as handle:
        for line in handle:
            if line.strip() and not line.lstrip().startswith("#"):
                break
            kept.append(line.rstrip("\n"))
    return "\n".join(kept).rstrip("\n")


def check(pin_path):
    pins = read_pins(pin_path)
    counts = census()
    failures, notes = [], []

    if pinned_header(pin_path) != HEADER:
        # The header states the two thresholds. Left unchecked, a change to
        # INLINE_MAX or XML_MAX would leave the file describing limits that
        # are no longer the ones being enforced.
        failures.append("%s does not carry the header its generator writes -"
                        " regenerate it rather than editing it by hand." % pin_path)

    for path in sorted(pins):
        if not os.path.isfile(path):
            failures.append("entry for a path that no longer exists: %s" % path)
            failures.append("  a rename has to move its counts with it, not drop it.")

    for path in sorted(set(counts) | set(pins)):
        if not os.path.isfile(path):
            continue
        actual = counts.get(path, {"inline": 0, "xml": 0})
        pinned = pins.get(path)
        if pinned is None:
            failures.append("%s: not in %s, and it has over-length blocks:"
                            % (path, pin_path))
            failures.extend(describe(path))
            continue
        for category in ("inline", "xml"):
            if actual[category] > pinned[category]:
                failures.append("%s: %d over-length %s blocks, pinned at %d"
                                % (path, actual[category], category, pinned[category]))
                failures.extend(describe(path, category))
            elif actual[category] < pinned[category]:
                notes.append("%s: %d over-length %s blocks, pin is %d"
                             % (path, actual[category], category, pinned[category]))

    if failures:
        print("The comment-block ratchet failed. It counts, per file, inline //")
        print("runs over %d lines and XML /// runs over %d, against %s."
              % (INLINE_MAX, XML_MAX, pin_path))
        print("")
        print("\n".join(failures))
        print("")
        print("Shorten the block and leave the caller-facing invariant inline, or")
        print("re-pin in this same commit and say why in the message:")
        print("  python3 tools/comment-budgets.py > %s" % pin_path)
        return 1

    for note in notes:
        print("NOTE: %s - re-pin to bank the reduction." % note)
    total_inline = sum(c["inline"] for c in counts.values())
    total_xml = sum(c["xml"] for c in counts.values())
    print("Over-length comment blocks: %d inline, %d xml, across %d files "
          "(all within their pins)." % (total_inline, total_xml, len(counts)))
    return 0


def describe(path, only=None):
    out = []
    for category, length, start in over_length_blocks(path):
        if only is None or category == only:
            out.append("  %s:%d: %d-line %s block" % (path, start, length, category))
    return out


def main(argv):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="fail if any file exceeds its pinned counts")
    parser.add_argument("--pins", default="docs/comment-budgets.txt")
    args = parser.parse_args(argv)

    if args.check:
        return check(args.pins)
    sys.stdout.write(render(census()))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
